<?php

use Automattic\WooCommerce\Admin\API\Reports\Categories\Query;

/**
 * The handler for the API calls to pipedrive.
 *
 * @link       https://customers.vizoo3d.com
 * @since      1.0.0
 *
 *
 * @package    Vizoo_Pipedrive
 * @subpackage Vizoo_Pipedrive/includes
 */

class Vizoo_Weclapp_API_Handler
{
    /**
     * Creates a quotation in weclapp.
     *
     * @since     1.0.0
     * @access    public
     * @param     string     $deal_type           ID for the type of the deal.
     * @param     string     $license_key         The license key.
     * @param     integer    $from_timestamp      dd
     * @param     integer    $to_timestamp        dd
     * @param     string     $customer_number     The weclapp customer number.
     * @param     string     $article_number      The weclapp article number.
     * @param     string     $discount            The discount percentage as string (without percent sign).
     * @param     string     $quantity            The quantity (=years of maintenance requested) as string.
     * @param     string     $tax_id              The id for the tax class.
     * @param     string     $unit_price          The price for a year of maintenance.
     * @param     array      $address             Address array used as delivery and invoice address.
     * @param     string     $mail_address        The customer's email address.
     * @param     string     $currency            Currency of the deal. Accepts a 3-character currency code (e.g. EUR, USD).
     * @param     string     $responsible_user    ID of the responsible user (Vizoo license manager).
     * @return    string                          The ID of the newly created quotation.
     */
    public static function create_quotation($deal_type, $license_key, $from_timestamp, $to_timestamp, $customer_number, $article_number, $discount, $quantity, $tax_id, $unit_price, $address, $mail_address, $currency_code, $responsible_user, &$quotation_number)
    {
        if (!is_numeric($customer_number)) {
            throw new \Exception("Invalid customer number. Not a number. Value: " . $customer_number);
        }
        $customer_party = self::get_party_from_customer_number($customer_number);
        $article = self::get_artice_from_article_number($article_number);
        $currency = self::get_currency_id_from_currency_code($currency_code);
        $args = [
            'customAttributes' => [
                [
                    'attributeDefinitionId' => '89868',
                    'selectedValueId' => $deal_type,
                ],
                [
                    'attributeDefinitionId' => '164663',
                    'stringValue' => '(auto-generated by maintenance and subscription workflow)',
                ],
            ],
            'customerId' => $customer_party['id'],
            'quotationDate' => (int)(new DateTimeImmutable())->format('Uv'),
            'quotationItems' => [
                [
                    'articleId' => $article['id'],
                    'discountPercentage' => $discount,
                    'manualQuantity' => true,
                    'manualUnitPrice' => true,
                    'quantity' => $quantity,
                    'taxId' => $tax_id,
                    'unitPrice' => $unit_price,
                    'customAttributes' => [
                        [
                            'attributeDefinitionId' => '72289',
                            'stringValue' => $license_key,
                        ],
                        [
                            'attributeDefinitionId' => '73006',
                            'dateValue' => $from_timestamp,
                        ],
                        [
                            'attributeDefinitionId' => '73018',
                            'dateValue' => $to_timestamp,
                        ],
                    ],
                ],
            ],
            'quotationType' => 'SALES_ORDER',
            'recordAddress' => $address,
            'recordEmailAddresses' => [
                'toAddresses' => $mail_address,
            ],
            'invoiceAddress' => $address,
            'deliveryAddress' => $address,
            'deliveryEmailAddresses' => [
                'toAddresses' => $mail_address,
            ],
            'recordCurrencyId' => $currency['id'],
            'salesInvoiceEmailAddresses' => [
                'toAddresses' => $mail_address,
            ],
        ];
        if ($responsible_user) {
            $args['responsibleUserId'] = $responsible_user;
        }
        $response = self::call_api('POST', 'quotation', array_filter($args));

        $quotation_number = $response['quotationNumber'];
        return $response['id'];
    }

    public static function create_subscription_quotation($license_id, $from_timestamp, $to_timestamp, $customer_number, $article_number, $discount, $quantity, $tax_id, $unit_price, $address, $mail_address, $currency_code, $responsible_user, &$quotation_number)
    {
        if (!is_numeric($customer_number)) {
            throw new \Exception("Invalid customer number. Not a number. Value: " . $customer_number);
        }
        $customer_party = self::get_party_from_customer_number($customer_number);
        $article = self::get_artice_from_article_number($article_number);
        $currency = self::get_currency_id_from_currency_code($currency_code);
        $args = [
            'customAttributes' => [
                [
                    // Custom attribute: VizooDealType (Vorgangstyp / Deal type)
                    'attributeDefinitionId' => '89868',
                    // Value: "Service (SW Subscription)"
                    'selectedValueId' => '1116223',
                ],
                [
                    'attributeDefinitionId' => '164663',
                    'stringValue' => '(auto-generated by maintenance and subscription workflow)',
                ],
            ],
            'customerId' => $customer_party['id'],
            'quotationDate' => (int)(new DateTimeImmutable())->format('Uv'),
            'quotationItems' => [
                [
                    'articleId' => $article['id'],
                    'discountPercentage' => $discount,
                    'manualQuantity' => true,
                    'manualUnitPrice' => true,
                    'quantity' => $quantity,
                    'taxId' => $tax_id,
                    'unitPrice' => $unit_price,
                    'customAttributes' => [
                        [
                            'attributeDefinitionId' => '72289',
                            'stringValue' => $license_id,
                        ],
                        [
                            'attributeDefinitionId' => '73006',
                            'dateValue' => $from_timestamp,
                        ],
                        [
                            'attributeDefinitionId' => '73018',
                            'dateValue' => $to_timestamp,
                        ],
                    ],
                ],
            ],
            'quotationType' => 'SALES_ORDER',
            'recordAddress' => $address,
            'recordEmailAddresses' => [
                'toAddresses' => $mail_address,
            ],
            'invoiceAddress' => $address,
            'deliveryAddress' => $address,
            'deliveryEmailAddresses' => [
                'toAddresses' => $mail_address,
            ],
            'recordCurrencyId' => $currency['id'],
            'salesInvoiceEmailAddresses' => [
                'toAddresses' => $mail_address,
            ],
        ];
        if ($responsible_user) {
            $args['responsibleUserId'] = $responsible_user;
        }
        $response = self::call_api('POST', 'quotation', array_filter($args));

        $quotation_number = $response['quotationNumber'];
        return $response['id'];
    }

    public static function create_quotation_pdf($quotation_id)
    {
        return self::call_api('POST', sprintf('quotation/id/%d/createQuotationPdf', $quotation_id), [], [], false);
    }

    private static function get_party_from_customer_number($customer_number)
    {
        $query_args = [
            'customerNumber-eq' => $customer_number,
        ];
        $response =  self::call_api('GET', 'party', [], $query_args);
        if (empty($response['result']) || !isset($response['result'][0]['id'])) {
            throw new RuntimeException("Unable to find party for customer number: " . $customer_number);
        }
        return $response['result'][0];
    }

    private static function get_artice_from_article_number($article_number)
    {
        $query_args = [
            'articleNumber-eq' => $article_number,
        ];
        $response = self::call_api('GET', 'article', [], $query_args);
        if (empty($response['result']) || !isset($response['result'][0]['id'])) {
            throw new RuntimeException("Unable to find article for article number: " . $article_number);
        }
        return $response['result'][0];
    }

    private static function get_currency_id_from_currency_code($currency_code)
    {
        $query_args = [
            'name-eq' => $currency_code,
        ];
        $response = self::call_api('GET', 'currency', [], $query_args);
        if (empty($response['result']) || !isset($response['result'][0]['id'])) {
            throw new RuntimeException("Unable to find currency id for currency code: " . $currency_code);
        }
        return $response['result'][0];
    }

    /**
     * Calls the weclapp API.
     *
     * @since     1.0.0
     * @access    private
     * @param     string     $method        The HTTP request method.
     * @param     string     $uri           Resource identifier.
     * @param     array      $postfields    Request body data.
     * @param     array      $query_args    Arguments to be added to the URL as query.
     * @return    array                     The data that is returned by the weclapp API.
     */
    private static function call_api($method, $uri, $postfields = [], $query_args = [], $parse_result = true)
    {
        $url = getenv('VIZOO_WECLAPP_API_ADDRESS') . $uri;

        if (!empty($query_args)) {
            $url .= '?' . http_build_query($query_args);
        }

        if (empty($postfields)) {
            $postfields = (object)$postfields;
        }

        $channel = curl_init();
        curl_setopt($channel, CURLOPT_ENCODING, 'gzip');
        curl_setopt($channel, CURLOPT_URL, $url);
        curl_setopt($channel, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($channel, CURLOPT_CUSTOMREQUEST, $method);
        curl_setopt($channel, CURLOPT_HTTPHEADER, [
            'Content-Type: application/json',
            'Accept: application/json',
            sprintf('AuthenticationToken: %s', getenv('VIZOO_WECLAPP_API_TOKEN')),
        ]);
        if ($method === 'POST' || $method === 'PUT') {
            curl_setopt($channel, CURLOPT_POSTFIELDS, json_encode($postfields));
        }
        $output = curl_exec($channel);

        $error_code = curl_errno($channel);
        $response_code = curl_getinfo($channel, CURLINFO_RESPONSE_CODE);

        curl_close($channel);
        if ($error_code !== 0) {
            throw new RuntimeException("The request to the weclapp API failed with error code $error_code.");
        }
        if ($response_code > 299) {
            throw new RuntimeException("The weclapp API returned HTTP status code $response_code.");
        }

        if (!$parse_result) {
            return $output;
        }
        return json_decode($output, true);
    }
}
