#!/bin/sh

# Aborts commits
#   - with non-ascii filenames
#   - that try to commit to master/_major/_minor/_patch
#   - that contain tabs
#   - that contain whitespaces errors (e.g. trailing whitespaces)

echo running pre-commit hook
if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
    # get current branch name
    local_branch=$(git rev-parse --abbrev-ref HEAD)
    # check if branch is protected (all upstream branches are considered protected)
    regex='^[:space:]*upstream\/([^[:space:]]+)[:space:]*$' # shorthand doesn't seem to work here, use POSIX syntax instead (see https://www.regular-expressions.info/posixbrackets.html)
    branch_is_protected=false
    while read -r line
    do
        if [[ $line =~ $regex ]];
        then
            if [[ $local_branch = ${BASH_REMATCH[1]} ]];
            then
                branch_is_protected=true
                break
            fi
        fi
    done <<< "$(git branch -r)"
    if [ "$branch_is_protected" = true ];
    then
        cat <<EOF
ERROR: Attempt to push to protected branch $local_branch

Please use a different branch.

To move your changes to another branch please use:
    git stash
    git checkout -b <newbranchname>
    git stash pop
EOF
        exit 1
    fi
else
    # Initial commit: diff against an empty tree object
    against=$(git hash-object -t tree /dev/null)
fi


# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if
    # Note that the use of brackets around a tr range is ok here, (it's
    # even required, for portability to Solaris 10's /usr/bin/tr), since
    # the square bracket bytes happen to fall in the designated range.
    test $(git diff --cached --name-only --diff-filter=A -z $against |
      LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
    cat <<EOF
ERROR: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

EOF
    exit 1
fi

# If there are tabs, print the offending file names and fail.
tabbedlines=$(
    git diff-index -U0 --cached $against |
    grep -P '^(?:\+\+\+|\+.*\t)' |                                                    # Grep added files and additions with TAB
    sed -rz 's/(^|\n)(\+\+\+[^\n]*\n)+(\+\+\+)/\1\3/' |                               # Of those files remove all that have no additions with TAB
    sed -rz 's/^\+\+\+[^\n]*?\n$//' |                                                 # The above may leave a single file with no TABs, if so remove this
    sed -r 's/^\+\+\+ (.*)$/\n\\033[0;31mERROR\\033[0m Found tab\(s\) in file \1:/' | # Reformat those file names and colorize ("+++ path/to/file.ext" -> "ERROR in file path/to/file.ext:")
    sed 's/^\+//' |                                                                   # Remove addition plus'
    sed 's/\t/\\033[0;41m TAB \\033[0m/g')                                            # Reformat tabs and colorize ("    " -> " TAB ")

if [[ -n "$tabbedlines" ]]; then
    echo -e "$tabbedlines"
    exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
